name: embench
channels:
  - aihabitat          # for habitat-sim
  - conda-forge
  - defaults
channel_priority: strict

dependencies:
  - python=3.9
  - pip
  # math / sci stack from conda (ABI-safe with scipy)
  - numpy=1.23
  - scipy=1.13.*
  - pandas=2.2.*
  - pillow=10.*        # (Pillow 11 works too, but keep aligned with conda)
  - matplotlib=3.9.*
  # UI/Qt from conda (avoid pip duplicates)
  - pyqt=5.15.*
  - qt-main=5.15.*
  # common libs you already had via conda (trimmed to key ones)
  - ffmpeg
  - imageio
  - imageio-ffmpeg
  - tqdm
  - typing_extensions
  - zlib
  - openssl
  - setuptools
  - wheel
  # (add any other conda packages you rely on from your list)

  - pip:
      # KEEP ONLY PACKAGES NOT (RELIABLY) AVAILABLE ON CONDA
      - accelerate==1.1.1
      - ai2thor==2.1.0
      - anthropic==0.43.0
      - datasets==3.1.0
      - fastapi==0.115.6
      - google-api-python-client==2.157.0
      - google-generativeai==0.8.3
      - huggingface-hub>=0.30.0
      - ipykernel==6.29.5
      - ipython==8.18.1            # Py3.9-compatible
      - jupyter_client==8.6.3
      - jupyter_core==5.7.2
      - jupyter-server==1.15.6      # pin 1.x for Py3.9
      - notebook_shim==0.2.4
      - numba==0.56.4
      - nvidia-cudnn-cu12==9.1.0.70
      - torch==2.4.0
      - torchvision==0.19.0
      - triton==3.0.0
      - transformers==4.49.0
      - uvicorn==0.32.1
      - ray==2.49.2
      - qwen-vl-utils==0.0.8
      # remove: numpy / pandas / matplotlib / pillow / PyQt5 / typing_extensions (now from conda)
      # remove: habitat-sim (will install from conda)
